### ISSUE TITLE
Backdrop click doesn't generate any event

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-crud#137] opened 2018-10-17 16:10 UTC
Click outside the editor doesn't generate any event, however it works similar to "Cancel".
1. When the editor is clean, backdrop click just closes the dialog.
In some cases I have to do navigation on closing the editor. 
2. When the editor is dirty, backdrop click does nothing.

**Comment by jouni** [comment] 2018-11-01 10:33
Seems almost like a duplicate of #94

**Comment by manolo** [comment] 2018-11-01 11:20
1.- You can listen to `editor-opened-changed`
2.- it's intentional to disable that feature when dirty, much more simple (#ffs) for first release, it will considered to cover in future versions

**Comment by manolo** [comment] 2018-11-02 14:55
Let's continue discussion in #94

**Closed by manolo** 2018-11-02 14:55 UTC
